name: GitHub Pages

on:
  push:
    tags:
      - "**"

jobs:
  publish:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/app

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: "echo 'shacl-playground.zazuko.com' > dist/CNAME"
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          build_dir: ./packages/app/dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
