name: Test

on: push

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@1.0.11
      - run: docker build -f Dockerfile -t shacl-playground .
